using System;
using System.Data;
using MySql.Data.MySqlClient;
using System.Windows.Forms;

namespace FormularioLogin 
{
	public static class DatabaseHelper
	{
		// Leer la cadena de conexión desde App.config
		private static string connectionString =
			System.Configuration.ConfigurationManager.ConnectionStrings["MiConexion"].ConnectionString;

		// Método para ejecutar consultas (INSERT, UPDATE, DELETE)
		public static int ExecuteNonQuery(string query, params MySqlParameter[] parameters)
		{
			try
			{
				using (MySqlConnection connection = new MySqlConnection(connectionString))
				{
					connection.Open();
					using (MySqlCommand command = new MySqlCommand(query, connection))
					{
						if (parameters != null)
							command.Parameters.AddRange(parameters);

						return command.ExecuteNonQuery();
					}
				}
			}
			catch (MySqlException ex)
			{
				MessageBox.Show($"Error de MySQL: {ex.Message}", "Error de Base de Datos", MessageBoxButtons.OK, MessageBoxIcon.Error);
				return -1;
			}
			catch (Exception ex)
			{
				MessageBox.Show($"Error general: {ex.Message}", "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
				return -1;
			}
		}

		// Método para ejecutar consultas que devuelven datos (SELECT)
		public static DataTable ExecuteQuery(string query, params MySqlParameter[] parameters)
		{
			DataTable dt = new DataTable();
			try
			{
				using (MySqlConnection connection = new MySqlConnection(connectionString))
				{
					connection.Open();
					using (MySqlCommand command = new MySqlCommand(query, connection))
					{
						if (parameters != null)
							command.Parameters.AddRange(parameters);

						using (MySqlDataReader reader = command.ExecuteReader())
						{
							dt.Load(reader);
						}
					}
				}
			}
			catch (MySqlException ex)
			{
				MessageBox.Show($"Error de MySQL: {ex.Message}", "Error de Base de Datos", MessageBoxButtons.OK, MessageBoxIcon.Error);
			}
			catch (Exception ex)
			{
				MessageBox.Show($"Error general: {ex.Message}", "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
			}

			return dt;
		}
	}
}
/*
 -- MySQL Script generated by MySQL Workbench
-- Sat Oct 11 12:46:52 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema club
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema club
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `club` DEFAULT CHARACTER SET utf8 ;
USE `club` ;

-- -----------------------------------------------------
-- Table `club`.`rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `club`.`rol` ;

CREATE TABLE IF NOT EXISTS `club`.`rol` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `club`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `club`.`usuario` ;

CREATE TABLE IF NOT EXISTS `club`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `contrasenia` NVARCHAR(250) NOT NULL,
  `rol_id` INT NOT NULL DEFAULT 1,
  `create_time` TIMESTAMP NOT NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_rol_idx` (`rol_id` ASC) VISIBLE,
  CONSTRAINT `fk_rol`
    FOREIGN KEY (`rol_id`)
    REFERENCES `club`.`rol` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `club`.`socio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `club`.`socio` ;

CREATE TABLE IF NOT EXISTS `club`.`socio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `dni` VARCHAR(11) NOT NULL,
  `fecha_nac` DATE NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `fecha_emision` DATE NOT NULL,
  `tipo` VARCHAR(20) NOT NULL,
  `estado` TINYINT NOT NULL DEFAULT 1,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `carnet` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `dni_UNIQUE` (`dni` ASC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- -----------------------------------------------------
-- Table `club`.`noSocio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `club`.`noSocio` ;

CREATE TABLE IF NOT EXISTS `club`.`noSocio` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `dni` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `dni_UNIQUE` (`dni` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `club`.`profesor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `club`.`profesor` ;

CREATE TABLE IF NOT EXISTS `club`.`profesor` (
  `id` INT NOT NULL,
  `especialidad` VARCHAR(45) NULL,
  `asistencia` VARCHAR(45) NULL,
  `sueldo_mensual` DECIMAL NULL,
  `fecha_ingreso` DATE NULL,
  `salon_asignado` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `club`.`actividad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `club`.`actividad` ;

CREATE TABLE IF NOT EXISTS `club`.`actividad` (
  `id` INT NOT NULL,
  `nombre_actividad` VARCHAR(45) NULL,
  `tipo` VARCHAR(45) NULL,
  `horario` INT NOT NULL,
  `profesor_id` INT NULL,
  `cupo_max` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `profesor_id_idx` (`profesor_id` ASC) VISIBLE,
  CONSTRAINT `profesor_id`
    FOREIGN KEY (`profesor_id`)
    REFERENCES `club`.`profesor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `club`.`cuota`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `club`.`cuota` ;

CREATE TABLE IF NOT EXISTS `club`.`cuota` (
  `id` INT NOT NULL,
  `monto` DECIMAL NOT NULL,
  `fecha_emision` DATE NOT NULL,
  `fecha_vencimiento` DATE NULL,
  `tipo` VARCHAR(45) NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `estado` TINYINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `club`.`inscripcion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `club`.`inscripcion` ;

CREATE TABLE IF NOT EXISTS `club`.`inscripcion` (
  `id` INT NOT NULL,
  `socio_id` INT NULL,
  `no_socio_id` INT NULL,
  `fecha_inscripcion` DATE NULL,
  `estado` TINYINT NULL,
  `inscripcioncol` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `socio_id_idx` (`socio_id` ASC) VISIBLE,
  INDEX `no_socio_id_idx` (`no_socio_id` ASC) VISIBLE,
  CONSTRAINT `socio_id`
    FOREIGN KEY (`socio_id`)
    REFERENCES `club`.`socio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `no_socio_id`
    FOREIGN KEY (`no_socio_id`)
    REFERENCES `club`.`noSocio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

 
 */